#!/usr/bin/env python3
import json
import matplotlib.pyplot as plt
import numpy as np
import argparse
import os

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Plot Density of States from"
                                     " a Json file generated by Phoebe")
    parser.add_argument("INPUT",
                        help="Name of the JSON file with the DoS")
    args = parser.parse_args()
    jfileName = args.INPUT

    # load in the json output
    with open(jfileName) as jfile:
        data = json.load(jfile)

    # unpack the json file
    try:
        dos = np.array(data['dos'])
    except KeyError:
        raise KeyError("DoS not found."
                       "Are you using the correct input json file?")

    energies = np.array(data['energies'])

    plt.figure(figsize=(6,2))
    energyLabel = r'Energy [' + data['energyUnit'] +']'

    # plot the bands
    plt.plot(energies, dos, lw=2, color='royalblue')

    # plot aesthetics
    plt.xlabel(energyLabel,fontsize=12)
    plt.ylabel(r'DoS [' + data['dosUnit'] + ']',fontsize=12)
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    plt.xlim(np.min(energies),np.max(energies))
    plt.ylim(None, np.max(dos)+np.max(dos)*0.1)

    plt.tight_layout()
    plotFileName = os.path.splitext(jfileName)[0] + ".pdf"
    plt.savefig(plotFileName)
    plt.show(block=False)
