#include <string>
#include "phononH0.h"
#include "electron_h0_fourier.h"

/** Class used to parse the raw data from quantum Espresso
 *
 */
class QEParser {
public:
	/** parsing of the force constants.
	 * @param fileName: name of the file generated by q2r.x containing the
	 * force constants
	 * @return sdt::tuple < Crystal, PhononH0 >: where crystal is the class with the
	 * information on the crystal structure, and PhononH0 is the class
	 * containing the force Constants and the functionality to compute the
	 * phonon energies.
	 */
	std::tuple<Crystal, PhononH0> parsePhHarmonic(const std::string fileName);

	/** parsing of the electronic band structure.
	 * @param fileName: name of the file generated by q2r.x containing the
	 * force constants
	 * @param fourierCutoff: a parameter used in the interpolation scheme.
	 * @return sdt::tuple < Crystal, FullPoints, ElectronH0Spline >: where crystal is
	 * the class with the information on the crystal structure, FullPoints
	 * is the class with the coarse grid of k-points, and ElectronH0Spline
	 * contains the band structure and the functionality to get the electronic
	 * energy at an arbitrary k-point.
	 */
	std::tuple<Crystal, FullPoints, ElectronH0Fourier> parseElHarmonicFourier(
			const std::string fileName, double& fourierCutoff);

//	void parseElHarmonicWan(int argc, char** argv);
//	void parseElPhAnharmonicEPA(int argc, char** argv);
//	void parseElphAnharmonicWan(int argc, char** argv);
//	void parsePhAnharmonicD3(int argc, char** argv);
};
